import os
from PIL import Image
import google.generativeai as genai
import asyncio

class ReporterAgent:
    def __init__(self, api_key: str = None):
        self.api_key = api_key
        if api_key:
            genai.configure(api_key=api_key)

    async def run(self, scraper_data: dict, analyst_data: dict) -> dict:
        """
        Uses a multimodal LLM to visually inspect the captured screenshot,
        cross-reference it with source code analyst findings, and produce a unified,
        premium cybersecurity forensic report.
        """
        screenshot_path = scraper_data.get("screenshot_path", "")
        url = scraper_data.get("url", "")
        title = scraper_data.get("title", "")
        indicators = analyst_data.get("indicators", [])
        ai_assessment = analyst_data.get("ai_threat_assessment", "No AI analysis performed.")
        
        # Calculate final threat score (average of rules and analyst AI score, or weighted)
        rule_score = analyst_data.get("rule_threat_score", 0)
        ai_score = analyst_data.get("ai_threat_score", rule_score)
        final_score = int(0.4 * rule_score + 0.6 * ai_score)
        
        # Determine threat level
        if final_score >= 70:
            threat_level = "🚨 CRITICAL / PHISHING CONFIRMED"
        elif final_score >= 40:
            threat_level = "⚠️ SUSPICIOUS / HIGH RISK"
        else:
            threat_level = "✅ SAFE / LOW RISK"

        visual_findings = "No visual inspection performed (No API Key or screenshot missing)."

        if self.api_key and screenshot_path and os.path.exists(screenshot_path):
            try:
                # Open image using Pillow
                img = Image.open(screenshot_path)
                
                # Visual analysis prompt
                prompt = f"""
You are a Senior Digital Forensics Specialist.
Review this screenshot of a suspect web page that we scanned: {url}

Here is the context of our investigation:
- Page Title: {title}
- Detected Threat Indicators: {[ind['description'] for ind in indicators]}
- Code Analyst Findings: {ai_assessment[:1000]}

Please visually inspect this screenshot:
1. Does it visually impersonate a trusted brand (e.g. Google Login, Microsoft, Facebook, Amazon, PayPal, or a bank)?
2. Are there indicators of deceptive design (e.g., mismatched logo and address bar, fake security seals, pressure tactics, poor resolution)?
3. What is your final verification verdict based entirely on the visual presentation?

Format your response in structured Markdown with headings:
- **Visual Identity Spoofing**: List any brands it attempts to impersonate.
- **Deceptive Visual Elements**: List any malicious design tricks seen.
- **Visual Verdict**: Summary of visual safety.
"""
                model = genai.GenerativeModel('gemini-1.5-flash')
                response = await asyncio.to_thread(model.generate_content, [prompt, img])
                visual_findings = response.text
            except Exception as e:
                visual_findings = f"Error during visual screenshot analysis: {str(e)}"

        # Generate a premium structured markdown report
        markdown_report = f"""# 🛡️ Autonomous Phishing Forensics Report

**Target URL:** `{url}`  
**Scan Timestamp:** `2026-05-22`  
**Security Verdict:** **{threat_level}**  
**Final Forensics Threat Score:** `{final_score} / 100`

---

## 📊 Executive Summary
This report was compiled autonomously by a collaborative Multi-Agent cybersecurity system. The system performed full headless browser interaction, analyzed DOM scripts and secure transmission signals, audited raw form elements, and completed a multimodal visual threat check on the suspect page screenshot.

---

## 🔴 Visual Inspection & Multimodal Audit
{visual_findings}

---

## 💻 Source Code & DOM Security Audit
### Suspicious Code Indicators
"""
        if not indicators:
            markdown_report += "\n* No high-risk static code indicators were flagged by rules.\n"
        else:
            for ind in indicators:
                markdown_report += f"\n- **[{ind['severity']}] {ind['type'].replace('_', ' ').title()}:** {ind['description']}"

        markdown_report += f"""

### AI Threat Code Assessment
{ai_assessment}

---

## 🛠️ System Artifacts
- **Rendered Screenshot File:** `{screenshot_path}`
- **Active DOM Structure length:** `{len(scraper_data.get('html', ''))} characters`
- **Total script tags scanned:** `{len(scraper_data.get('scripts', []))}`
- **Total input forms scanned:** `{len(scraper_data.get('forms', []))}`

---
*Generated by the Multi-Agent Phishing Forensics Engine. Confidentially secured.*
"""

        # Save markdown report to disk
        reports_dir = "reports"
        os.makedirs(reports_dir, exist_ok=True)
        safe_name = "".join([c if c.isalnum() else "_" for c in url])[:50]
        report_path = os.path.join(reports_dir, f"report_{safe_name}.md")
        
        with open(report_path, "w") as f:
            f.write(markdown_report)

        return {
            "threat_level": threat_level,
            "final_score": final_score,
            "visual_findings": visual_findings,
            "markdown_report": markdown_report,
            "report_path": report_path
        }
